// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1PI6YpDzOJYTbNL4-87-TtKzlbaoaAY',
    appId: '1:783756044698:web:3cdef37c2e1fa4b9233223',
    messagingSenderId: '783756044698',
    projectId: 'finaluygulama2',
    authDomain: 'finaluygulama2.firebaseapp.com',
    storageBucket: 'finaluygulama2.appspot.com',
    measurementId: 'G-BQP8PY56MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7vZbRRHl9Wgja16KDQEarsVziUxw6Gs',
    appId: '1:783756044698:android:19bb14728328b13c233223',
    messagingSenderId: '783756044698',
    projectId: 'finaluygulama2',
    storageBucket: 'finaluygulama2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTHcuXg_z0cj_WXJUKiPDWU2lmrC85CgU',
    appId: '1:783756044698:ios:1b02978589d2b329233223',
    messagingSenderId: '783756044698',
    projectId: 'finaluygulama2',
    storageBucket: 'finaluygulama2.appspot.com',
    iosBundleId: 'com.example.finalUygulama2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTHcuXg_z0cj_WXJUKiPDWU2lmrC85CgU',
    appId: '1:783756044698:ios:21dca024f33d6dbf233223',
    messagingSenderId: '783756044698',
    projectId: 'finaluygulama2',
    storageBucket: 'finaluygulama2.appspot.com',
    iosBundleId: 'com.example.finalUygulama2.RunnerTests',
  );
}
